version: '2'
services:
  node-app:
    build:
      context: .
      dockerfile: node.Dockerfile
    ports:
      - 3333:3000
  nginx-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4444:3000
